#include "../include/deck_data.hpp"

using enum card_data::CardID;


static constexpr std::array<card_data::CardID, 54> kStandardDeck = {
    // Dominance
    kMouseDominance,
    kFoxDominance,
    kRabbitDominance,
    kBirdDominance,

    // Ambush
    kMouseAmbush,
    kFoxAmbush,
    kRabbitAmbush,
    kBirdAmbush,
    kBirdAmbush,

    // Items & Gear
    kMouseInASack,
    kGentlyUsedKnapsack,
    kSmugglersTrail,
    kBirdyBindle,
    kMouseTravelGear,
    kFoxTravelGear,
    kAVisitToFriends,
    kWoodlandRunners,
    kAnvil,
    kSword,
    kFoxfolkSteel,
    kArmsTrader,
    kMouseRootTea,
    kFoxRootTea,
    kRabbitRootTea,
    kInvestments,
    kProtectionRacket,
    kBakeSale,
    kMouseCrossbow,
    kBirdCrossbow,

    // Standard deck unique cards
    kFavorOfTheMice,
    kFavorOfTheFoxes,
    kFavorOfTheRabbits,
    kCodebreakers,
    kCodebreakers,
    kScoutingParty,
    kScoutingParty,
    kStandAndDeliver,
    kStandAndDeliver,
    kTaxCollector,
    kTaxCollector,
    kTaxCollector,
    kBetterBurrowBank,
    kBetterBurrowBank,
    kCobbler,
    kCobbler,
    kCommandWarren,
    kCommandWarren,
    kArmorers,
    kArmorers,
    kBrutalTactics,
    kBrutalTactics,
    kRoyalClaim,
    kSappers,
    kSappers,
};

static constexpr std::array<card_data::CardID, 54> kExilesAndPartisansDeck = {
    // Dominance
    kMouseDominance,
    kFoxDominance,
    kRabbitDominance,
    kBirdDominance,

    // Ambush
    kMouseAmbush,
    kFoxAmbush,
    kRabbitAmbush,
    kBirdAmbush,
    kBirdAmbush,

    // Items & Gear
    kMouseInASack,
    kGentlyUsedKnapsack,
    kSmugglersTrail,
    kBirdyBindle,
    kMouseTravelGear,
    kFoxTravelGear,
    kAVisitToFriends,
    kWoodlandRunners,
    kAnvil,
    kSword,
    kFoxfolkSteel,
    kArmsTrader,
    kMouseRootTea,
    kFoxRootTea,
    kRabbitRootTea,
    kInvestments,
    kProtectionRacket,
    kBakeSale,
    kMouseCrossbow,
    kBirdCrossbow,

    // Exiles & Partisans unique cards
    kMousePartisans,
    kFoxPartisans,
    kRabbitPartisans,
    kLeagueOfAdventurousMice,
    kLeagueOfAdventurousMice,
    kMasterEngravers,
    kMurineBroker,
    kCharmOffensive,
    kCoffinMakers,
    kSwapMeet,
    kSwapMeet,
    kTunnels,
    kTunnels,
    kFalseOrders,
    kFalseOrders,
    kInformants,
    kInformants,
    kPropagandaBureau,
    kBoatBuilders,
    kCorvidPlanners,
    kEyrieÉmigré,
    kSaboteurs,
    kSaboteurs,
    kSaboteurs,
    kSoupKitchens,
};