#include "../include/deck_data.hpp"

using enum CardID;


const std::array<CardID, 54> STANDARD_DECK = {
    // Dominance
    MouseDominance,
    FoxDominance,
    RabbitDominance,
    BirdDominance,

    // Ambush
    MouseAmbush,
    FoxAmbush,
    RabbitAmbush,
    BirdAmbush,
    BirdAmbush,

    // Items & Gear
    MouseInASack,
    GentlyUsedKnapsack,
    SmugglersTrail,
    BirdyBindle,
    MouseTravelGear,
    FoxTravelGear,
    AVisitToFriends,
    WoodlandRunners,
    Anvil,
    Sword,
    FoxfolkSteel,
    ArmsTrader,
    MouseRootTea,
    FoxRootTea,
    RabbitRootTea,
    Investments,
    ProtectionRacket,
    BakeSale,
    MouseCrossbow,
    BirdCrossbow,

    // Standard deck unique cards
    FavorOfTheMice,
    FavorOfTheFoxes,
    FavorOfTheRabbits,
    Codebreakers,
    Codebreakers,
    ScoutingParty,
    ScoutingParty,
    StandAndDeliver,
    StandAndDeliver,
    TaxCollector,
    TaxCollector,
    TaxCollector,
    BetterBurrowBank,
    BetterBurrowBank,
    Cobbler,
    Cobbler,
    CommandWarren,
    CommandWarren,
    Armorers,
    Armorers,
    BrutalTactics,
    BrutalTactics,
    RoyalClaim,
    Sappers,
    Sappers,
};

const std::array<CardID, 54> EXILES_AND_PARTISANS_DECK = {
    // Dominance
    MouseDominance,
    FoxDominance,
    RabbitDominance,
    BirdDominance,

    // Ambush
    MouseAmbush,
    FoxAmbush,
    RabbitAmbush,
    BirdAmbush,
    BirdAmbush,

    // Items & Gear
    MouseInASack,
    GentlyUsedKnapsack,
    SmugglersTrail,
    BirdyBindle,
    MouseTravelGear,
    FoxTravelGear,
    AVisitToFriends,
    WoodlandRunners,
    Anvil,
    Sword,
    FoxfolkSteel,
    ArmsTrader,
    MouseRootTea,
    FoxRootTea,
    RabbitRootTea,
    Investments,
    ProtectionRacket,
    BakeSale,
    MouseCrossbow,
    BirdCrossbow,

    // Exiles & Partisans unique cards
    MousePartisans,
    FoxPartisans,
    RabbitPartisans,
    LeagueOfAdventurousMice,
    LeagueOfAdventurousMice,
    MasterEngravers,
    MurineBroker,
    CharmOffensive,
    CoffinMakers,
    SwapMeet,
    SwapMeet,
    Tunnels,
    Tunnels,
    FalseOrders,
    FalseOrders,
    Informants,
    Informants,
    PropagandaBureau,
    BoatBuilders,
    CorvidPlanners,
    EyrieÉmigré,
    Saboteurs,
    Saboteurs,
    Saboteurs,
    SoupKitchens,
};